apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: webhook-server
        image: quay.io/openshift/origin-metallb:4.14
        securityContext:
          $patch: delete
        env:
          - name: METALLB_BGP_TYPE
            value: frr
        command:
          - /controller
      securityContext:
        $patch: delete
